#!/bin/bash
# Quick fix script for VPS deployment issues

echo "🔧 VPS Deployment Fix Script"
echo "============================"
echo ""
echo "This script will help fix common deployment issues."
echo ""

VPS_HOST="72.61.71.4"
VPS_USER="root"
VPS_PATH="/root/youtube-crypto-bot"

echo "Run these commands on your VPS (ssh root@72.61.71.4):"
echo ""
echo "1. Check PM2 logs:"
echo "   pm2 logs youtube-crypto-bot --lines 50"
echo ""
echo "2. Check if files exist:"
echo "   cd $VPS_PATH"
echo "   ls -la"
echo "   ls -la dist/"
echo "   ls -la client/dist/"
echo ""
echo "3. Check if .env exists:"
echo "   test -f .env && echo '✅ .env exists' || echo '❌ .env missing'"
echo ""
echo "4. Rebuild and restart:"
echo "   cd $VPS_PATH"
echo "   npm install"
echo "   cd client && npm install && cd .."
echo "   npm run build"
echo "   pm2 delete youtube-crypto-bot"
echo "   pm2 start ecosystem.config.js"
echo "   pm2 save"
echo ""
echo "5. Check status:"
echo "   pm2 status"
echo "   pm2 logs youtube-crypto-bot --lines 20"
echo ""

